# Generated by Django 6.0.4 on 2026-04-13 22:07

import re

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_kiosk_role(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    Role.objects.get_or_create(
        name='Kiosk',
        defaults={'description': 'Auto-created role for kiosk service accounts'},
    )


def extract_national_ids(apps, schema_editor):
    """Extract national IDs from Customer.notes (pattern: Cédula: V-XX.XXX.XXX)."""
    Customer = apps.get_model('core', 'Customer')
    pattern = re.compile(r'[Cc][eé]dula:\s*([VvEePp]-?[\d.]+)')
    for customer in Customer.objects.filter(notes__icontains='dula'):
        match = pattern.search(customer.notes)
        if match:
            raw = match.group(1).replace('.', '').strip()
            # Only set if not already populated and not a duplicate
            if not customer.national_id:
                if not Customer.objects.filter(national_id=raw).exists():
                    customer.national_id = raw
                    customer.save(update_fields=['national_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_user_language_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff'), ('Kiosk', 'Kiosk')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='KioskStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_identifier', models.CharField(max_length=50)),
                ('station_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('api_key_prefix', models.CharField(db_index=True, max_length=8)),
                ('api_key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_rate', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Probability (0.00–1.00) that a checkout triggers employee verification.', max_digits=3)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioned_stations', to=settings.AUTH_USER_MODEL)),
                ('service_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kiosk_station', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiosk Station',
                'unique_together': {('store_identifier', 'station_number')},
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.salesorder')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='core.kioskstation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
            },
        ),
        migrations.RunPython(seed_kiosk_role, migrations.RunPython.noop),
        migrations.RunPython(extract_national_ids, migrations.RunPython.noop),
    ]
