# Generated by Django 6.0.4 on 2026-04-19 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_currency_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_currency_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_currency_symbol',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_decimal_places',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=20),
        ),
    ]
