# Generated by Django 6.0.4 on 2026-05-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings_secondary_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ocr_receipt_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='origin_bank',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='origin_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient_bank',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_key',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_api_key',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_base_url',
            field=models.URLField(default='https://vepay-api.fly.dev'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_enabled_methods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_max_file_mb',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_provider',
            field=models.CharField(choices=[('vepay', 'VEPay')], default='vepay', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_require_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_strict_amount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_timeout_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_payment', 'Mobile Payment'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('check', 'Check'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_key__gt', '')), fields=('transaction_key',), name='payment_transaction_key_unique_when_set'),
        ),
    ]
