# Generated by Django 4.2.30 on 2026-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemsettings_ocr_base_url_no_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_rate_auto_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_rate_source_field',
            field=models.CharField(blank=True, default='promedio', help_text='Dotted path to the numeric rate in the source JSON, e.g. "promedio" or "data.rate".', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_rate_source_url',
            field=models.URLField(blank=True, default='https://ve.dolarapi.com/v1/dolares/oficial'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_rate_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
