# Generated by Django 4.2.30 on 2026-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_secondary_rate_auto_update_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ocr_enabled_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
