# Generated by Django 4.2.30 on 2026-07-23 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_secondary_rate_auto_update_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='recipient_validation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(choices=[('mobile_payment', 'Mobile Payment'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=120)),
                ('document_id', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recipient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipient Profile',
                'verbose_name_plural': 'Recipient Profiles',
                'ordering': ['payment_method', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipientprofile',
            constraint=models.UniqueConstraint(fields=('payment_method', 'phone', 'bank', 'document_id'), name='recipient_profile_unique_combo'),
        ),
    ]
