# Generated by Django 4.2.30 on 2026-07-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_systemsettings_ocr_enabled_methods'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipientprofile',
            name='recipient_profile_unique_combo',
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='recipientprofile',
            constraint=models.UniqueConstraint(fields=('payment_method', 'phone', 'account_number', 'bank', 'document_id'), name='recipient_profile_unique_combo'),
        ),
    ]
