# Generated by Django 4.2.30 on 2026-07-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_recipientprofile_recipient_profile_unique_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='recipientprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('payment_method', 'is_primary'), name='recipient_profile_one_primary_per_method'),
        ),
    ]
