# Generated by Django 4.2.30 on 2026-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_backfill_sole_recipient_profile_primary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['-created_at'], name='invmovement_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-created_at'], name='salesorder_created_idx'),
        ),
    ]
