# Generated by Django 4.2.30 on 2026-09-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_created_at_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.UniqueConstraint(fields=('sales_order', 'product'), name='salesorderitem_unique_product_per_order'),
        ),
    ]
